/**
 * DESIGN.md frontmatter → tokens.generated.css + motion.generated.ts + copy.generated.ts
 * Authority: AD-16 / AD-20. Run via `npm run gen:tokens`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(__dirname, '..');
const designPath = resolve(
  packageRoot,
  '../_bmad-output/planning-artifacts/ux-designs/ux-mind-void-2026-07-25/DESIGN.md',
);

const BANNER_CSS =
  '/* Generated by scripts/gen-tokens.ts — do not hand-edit. */\n';
const BANNER_TS =
  '/** Generated by scripts/gen-tokens.ts — do not hand-edit. */\n';

type StringMap = Record<string, string>;
type NestedMaps = Record<string, StringMap>;

function extractFrontmatter(markdown: string): string {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(markdown);
  if (!match) {
    throw new Error(`No YAML frontmatter found in ${designPath}`);
  }
  return match[1] ?? '';
}

/** Minimal YAML map parser for DESIGN.md frontmatter (string values + one nesting level). */
function parseDesignFrontmatter(yaml: string): {
  colors: StringMap;
  typography: NestedMaps;
  rounded: StringMap;
  spacing: StringMap;
  motion: StringMap;
} {
  const lines = yaml.split(/\r?\n/);
  const root: Record<string, StringMap | NestedMaps> = {};
  let section: string | null = null;
  let sub: string | null = null;

  for (const raw of lines) {
    if (!raw.trim() || raw.trimStart().startsWith('#')) continue;

    const top = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(raw);
    const nested = /^  ([A-Za-z0-9_.-]+|'[^']+'|"[^"]+"):\s*(.*)$/.exec(raw);
    const deep = /^    ([A-Za-z0-9_-]+|'[^']+'|"[^"]+"):\s*(.*)$/.exec(raw);

    if (top && !raw.startsWith(' ')) {
      const key = top[1]!;
      const rest = top[2]!.trim();
      section = key;
      sub = null;
      if (rest === '') {
        root[key] = {};
      } else {
        // scalar at root (name, description, status, updated) — ignore for tokens
        section = null;
      }
      continue;
    }

    if (deep && section && sub) {
      const nest = root[section] as NestedMaps;
      if (!nest[sub]) nest[sub] = {};
      nest[sub]![stripQuotes(deep[1]!)] = stripQuotes(deep[2]!.trim());
      continue;
    }

    if (nested && section) {
      const key = stripQuotes(nested[1]!);
      const rest = nested[2]!.trim();
      if (rest === '') {
        sub = key;
        const nest = root[section] as NestedMaps;
        nest[key] = {};
      } else {
        sub = null;
        (root[section] as StringMap)[key] = stripQuotes(rest);
      }
    }
  }

  const colors = (root.colors as StringMap) ?? {};
  const motion = (root.motion as StringMap) ?? {};
  const spacing = (root.spacing as StringMap) ?? {};
  const rounded = (root.rounded as StringMap) ?? {};
  const typography = (root.typography as NestedMaps) ?? {};

  if (Object.keys(colors).length === 0) {
    throw new Error('DESIGN.md frontmatter missing colors');
  }
  if (Object.keys(motion).length === 0) {
    throw new Error('DESIGN.md frontmatter missing motion');
  }

  return { colors, typography, rounded, spacing, motion };
}

function stripQuotes(value: string): string {
  if (
    (value.startsWith("'") && value.endsWith("'")) ||
    (value.startsWith('"') && value.endsWith('"'))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function ms(token: string): number {
  const m = /^(\d+(?:\.\d+)?)ms$/.exec(token.trim());
  if (!m) {
    throw new Error(`Expected duration in ms, got: ${token}`);
  }
  return Number(m[1]);
}

function emitCss(data: {
  colors: StringMap;
  spacing: StringMap;
  rounded: StringMap;
  typography: NestedMaps;
  motion: StringMap;
}): string {
  const lines: string[] = [BANNER_CSS, '.mv-shell {'];

  for (const [key, value] of Object.entries(data.colors)) {
    lines.push(`  --mv-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(data.spacing)) {
    lines.push(`  --mv-space-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(data.rounded)) {
    lines.push(`  --mv-rounded-${key}: ${value};`);
  }
  for (const [role, props] of Object.entries(data.typography)) {
    for (const [prop, value] of Object.entries(props)) {
      const kebab = prop.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
      lines.push(`  --mv-type-${role}-${kebab}: ${value};`);
    }
  }
  for (const [key, value] of Object.entries(data.motion)) {
    lines.push(`  --mv-motion-${key}: ${value};`);
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function emitMotionTs(motion: StringMap): string {
  const full = {
    holdCommit: ms(motion['hold-commit']!),
    eliminateDissolve: ms(motion['eliminate-dissolve']!),
    redistribute: ms(motion['redistribute']!),
    fuseMagnetize: ms(motion['fuse-magnetize']!),
    seamFlash: ms(motion['seam-flash']!),
    solidSettle: ms(motion['solid-settle']!),
    thesisHold: 4000,
    previewIn: ms(motion['preview-in']!),
    previewOut: ms(motion['preview-out']!),
    pulseIdle: ms(motion['pulse-idle']!),
    easeCalm: motion['ease-calm']!,
    easeMagnetize: motion['ease-magnetize']!,
    idlePulse: true,
    ambientDrift: true,
    settleOvershoot: true,
  };

  // Reduced overrides — Architecture memlog / AD-5 / UX-DR15
  const reduced = {
    ...full,
    eliminateDissolve: 120,
    redistribute: 0,
    fuseMagnetize: 120,
    solidSettle: 0,
    idlePulse: false,
    ambientDrift: false,
    settleOvershoot: false,
  };

  return `${BANNER_TS}
export type MotionProfile = {
  holdCommit: number;
  eliminateDissolve: number;
  redistribute: number;
  fuseMagnetize: number;
  seamFlash: number;
  solidSettle: number;
  thesisHold: number;
  previewIn: number;
  previewOut: number;
  pulseIdle: number;
  easeCalm: string;
  easeMagnetize: string;
  idlePulse: boolean;
  ambientDrift: boolean;
  settleOvershoot: boolean;
};

export const motionFull = ${JSON.stringify(full, null, 2)} as const satisfies MotionProfile;

export const motionReduced = ${JSON.stringify(reduced, null, 2)} as const satisfies MotionProfile;
`;
}

function emitCopyTs(): string {
  return `${BANNER_TS}
export const productCopy = {
  hint: 'something here is unresolved.',
  thesis: 'closure, not checkboxes.',
  architectureCredit:
    'InputAdapter → FSM → DomView + EffectBus → ParticleEngine',
  /** Accessible names for shard bodies (AD-25) — index matches shard order. */
  optionLabels: [
    'Option A',
    'Option B',
    'Option C',
    'Option D',
    'Option E',
  ],
  decisionNodeLabel: 'Unresolved decision',
} as const;

export type ProductCopy = typeof productCopy;
`;
}

function main(): void {
  const markdown = readFileSync(designPath, 'utf8');
  const data = parseDesignFrontmatter(extractFrontmatter(markdown));

  const cssPath = join(packageRoot, 'src/styles/tokens.generated.css');
  const motionPath = join(packageRoot, 'src/core/motion.generated.ts');
  const copyPath = join(packageRoot, 'src/core/copy.generated.ts');

  mkdirSync(dirname(cssPath), { recursive: true });
  writeFileSync(cssPath, emitCss(data), 'utf8');
  writeFileSync(motionPath, emitMotionTs(data.motion), 'utf8');
  writeFileSync(copyPath, emitCopyTs(), 'utf8');

  console.log(`Wrote ${cssPath}`);
  console.log(`Wrote ${motionPath}`);
  console.log(`Wrote ${copyPath}`);
}

main();
