/** Generated by scripts/gen-tokens.ts — do not hand-edit. */

export const productCopy = {
  hint: 'something here is unresolved.',
  thesis: 'closure, not checkboxes.',
  architectureCredit:
    'InputAdapter → FSM → DomView + EffectBus → ParticleEngine',
} as const;

export type ProductCopy = typeof productCopy;
