/** Generated by scripts/gen-tokens.ts — do not hand-edit. */

export type MotionProfile = {
  holdCommit: number;
  eliminateDissolve: number;
  redistribute: number;
  fuseMagnetize: number;
  seamFlash: number;
  solidSettle: number;
  thesisHold: number;
  previewIn: number;
  previewOut: number;
  pulseIdle: number;
  easeCalm: string;
  easeMagnetize: string;
  idlePulse: boolean;
  ambientDrift: boolean;
  settleOvershoot: boolean;
};

export const motionFull = {
  "holdCommit": 400,
  "eliminateDissolve": 220,
  "redistribute": 300,
  "fuseMagnetize": 260,
  "seamFlash": 120,
  "solidSettle": 320,
  "thesisHold": 4000,
  "previewIn": 120,
  "previewOut": 180,
  "pulseIdle": 3200,
  "easeCalm": "cubic-bezier(0.4, 0.0, 0.2, 1)",
  "easeMagnetize": "cubic-bezier(0.2, 0.8, 0.2, 1)",
  "idlePulse": true,
  "ambientDrift": true,
  "settleOvershoot": true
} as const satisfies MotionProfile;

export const motionReduced = {
  "holdCommit": 400,
  "eliminateDissolve": 120,
  "redistribute": 0,
  "fuseMagnetize": 120,
  "seamFlash": 120,
  "solidSettle": 0,
  "thesisHold": 4000,
  "previewIn": 120,
  "previewOut": 180,
  "pulseIdle": 3200,
  "easeCalm": "cubic-bezier(0.4, 0.0, 0.2, 1)",
  "easeMagnetize": "cubic-bezier(0.2, 0.8, 0.2, 1)",
  "idlePulse": false,
  "ambientDrift": false,
  "settleOvershoot": false
} as const satisfies MotionProfile;
